apiVersion: apps/v1
kind: Service
metadata:
  name: mongo-svc
  namespace: workshop
  
spec: 
  selector:
    app: mongoDb
  ports:
  - name: mongo-svc
    protocol: TCP
    port: 27017
    targetPort: 27017